name: Onboard GCP Project

on:
    push:
      branches: [main]
      paths:
        - 'env.json'
        - '.github/workflows/onboard-gcp-project.yaml'
    workflow_dispatch:

jobs:
  onboard:
    uses: subhamay-bhattacharyya-gha/gcp-project-onboarding/.github/workflows/gcp-project-onboarding.yaml@feature/GHA-0001-feat-implement-initial-re
    secrets: inherit
